networks: {}
services:
  db:
    image: postgres:9.4
    volumes:
    - db-data:/var/lib/postgresql/data:rw
  redis:
    image: redis:alpine
  result:
    build:
      context: /Users/campbel/git/example-voting-app/result
    command: nodemon --debug server.js
    image: campbel/votingapp-result:latest
    ports:
    - 8001:80/tcp
    volumes:
    - /Users/campbel/git/example-voting-app/result:/app:rw
  test:
    build:
      context: /Users/campbel/git/example-voting-app/tests
    depends_on:
    - result
    - vote
    - worker
  vote:
    build:
      context: /Users/campbel/git/example-voting-app/vote
    command: python app.py
    image: campbel/votingapp-vote:latest
    ports:
    - 8000:80/tcp
    volumes:
    - /Users/campbel/git/example-voting-app/vote:/app:rw
  worker:
    build:
      context: /Users/campbel/git/example-voting-app/worker
    image: campbel/votingapp-worker:latest
version: '2.0'
volumes:
  db-data: {}

